const fs = require('fs');
const path = require('path');
// eslint-disable-next-line import/no-extraneous-dependencies
const jsdom = require('jsdom');

// Configuration
const CONFIG = {
  iconPrefix: '', // Optionnel: préfixe pour tous les noms d'icônes
  outputFile: process.argv[3] || 'src/constants/ICONS.ts',
  svgDir: process.argv[2] || 'tools/svg-2-obj/svg',
};

function convertSvgToIcons() {
  const svgPath = path.resolve(process.cwd(), CONFIG.svgDir);

  if (!fs.existsSync(svgPath)) {
    console.error(`❌ Directory not found: ${svgPath}`);
    process.exit(1);
  }

  const files = fs.readdirSync(svgPath);
  const icons = {};
  let successCount = 0;
  let errorCount = 0;

  files.forEach(file => {
    const filePath = path.join(svgPath, file);
    const [fileName, fileExt] = file.split('.');

    if (fileExt !== 'svg') return;

    try {
      const fileContent = fs.readFileSync(filePath, 'utf8');
      const dom = new jsdom.JSDOM(fileContent);
      const svg = dom.window.document.querySelector('svg');

      if (!svg) {
        console.warn(`⚠️  No SVG element found in ${file}`);
        errorCount += 1;
        return;
      }

      const viewBox = svg.getAttribute('viewBox') || '0 0 24 24';
      const paths = [];
      const pathElements = dom.window.document.querySelectorAll('path');

      pathElements.forEach(element => {
        const pathD = element.getAttribute('d');
        if (pathD && pathD.trim() !== '') {
          paths.push(pathD);
        }
      });

      if (paths.length === 0) {
        console.warn(`⚠️  No paths found in ${file}`);
        errorCount += 1;
        return;
      }

      const iconName = CONFIG.iconPrefix + fileName;
      icons[iconName] = { path: paths, viewBox };
      successCount += 1;
    } catch (error) {
      console.error(`❌ Error processing ${file}:`, error.message);
      errorCount += 1;
    }
  });

  if (Object.keys(icons).length === 0) {
    console.error('❌ No icons generated');
    process.exit(1);
  }

  const iconObj = JSON.stringify(icons, null, 2);
  const output = `// Auto-generated by svg-to-icons script
// Do not edit manually

export const ICONS = ${iconObj} as const;

export type TIcons = typeof ICONS;
export type TIconName = keyof TIcons;
export const ICONS_OPTIONS = Object.keys(ICONS) as TIconName[];
`;

  const outputPath = path.resolve(process.cwd(), CONFIG.outputFile);
  fs.writeFileSync(outputPath, output);

  console.log('\n✅ Icons generated successfully!');
  console.log(`   Success: ${successCount} icons`);
  if (errorCount > 0) {
    console.log(`   Errors: ${errorCount} files`);
  }
  console.log(`   Output: ${outputPath}\n`);
}

convertSvgToIcons();
